stages:
  _split:
    cmd: python src/data/data_split.py
    deps:
      - data/raw_data/raw.csv
      - src/data/data_split.py
    outs:
      - data/processed_data/X_train.csv
      - data/processed_data/X_test.csv
      - data/processed_data/y_train.csv
      - data/processed_data/y_test.csv

  _normalize:
    cmd: python src/data/normalize.py
    deps:
      - data/processed_data/X_train.csv
      - data/processed_data/X_test.csv
      - src/data/normalize.py
    outs:
      - data/processed_data/X_train_scaled.csv
      - data/processed_data/X_test_scaled.csv
      - models/data/scaler.pkl

  _gridsearch:
    cmd: python src/models/grid_search.py
    deps:
      - data/processed_data/X_train_scaled.csv
      - data/processed_data/y_train.csv
      - src/models/grid_search.py
    outs:
      - models/data/best_params.pkl

  _training:
    cmd: python src/models/training.py
    deps:
      - data/processed_data/X_train_scaled.csv
      - data/processed_data/y_train.csv
      - models/data/best_params.pkl
      - src/models/training.py
    outs:
      - models/models/gbr_model.pkl

  _evaluate:
    cmd: python src/models/evaluate.py
    deps:
      - models/models/gbr_model.pkl
      - data/processed_data/X_test_scaled.csv
      - data/processed_data/y_test.csv
      - src/models/evaluate.py
    outs:
      - data/processed_data/predictions.csv
      - metrics/scores.json
